
export const ProductsData = [
    {
      id: 1,
      price: 2.25,
      amount: 0,
      name: "Camilo Diaz - Gear Third",
      img: "./img/BPR165.jpg", 
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 2,
      price: 2.50 ,
      amount: 0,
      name: "Camilo Diaz - Vagabundo",
      img: "./img/BPR164.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 3,
      price: 1.99,
      amount: 0,
      name: "Rolando De Leon - Grasslight",
      img: "./img/BPR163.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 4,
      price: 1.50,
      amount: 0,
      name: "The Sahoo Connection - Be Water",
      img: "./img/BPR162.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 5,
      price: 1.50,
      amount: 0,
      name: "Newball - Chicago",
      img: "./img/BPR161.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 6,
      price: 1.35,
      amount: 0,
      name: "Camilo Diaz - Back To Basics",
      img: "./img/BPR160.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 7,
      price: 0.99,
      amount: 0,
      name: "ICK - Slowly",
      img: "./img/BPR159.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 8,
      price: 0.99,
      amount: 0,
      name: "Funky Disco - Caesar",
      img: "./img/BPR158.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 9,
      price: 0.99,
      amount: 0,
      name: "The Sahoo Connection - Orilla",
      img: "./img/BPR157.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 10,
      price: 0.99,
      amount: 0,
      name: "Cambodia - Maria",
      img: "./img/BPR156.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
    {
      id: 11,
      price: 0.99,
      amount: 0,
      name: "Brandon Caballero & Drumbeat - Dancefloor",
      img: "./img/BPR155.jpg",
      ReleaseDate: "2022-06-21",
      Artist: "Camilo Diaz",
      Copyright: "All Right Reserved - Bullet Proof Records",
      Tracks: "Gear Third (Original Mix) - Boundman (Original Mix)",
    },
  ];